@startuml
hide empty description
[*] --> SpawningState
SpawningState --> BuildingState : CSites present
SpawningState --> RepairingState : No CSites

BuildingState --> BuildingState : Working
BuildingState --> BuildingState : CSite no longer exist
BuildingState --> RefillingState : No resources\non hand
BuildingState --> RepairingState : No CSites
BuildingState --> MovingState : Out of range

RefillingState --> BuildingState : Resources full\nCSites present
RefillingState --> RepairingState : No CSites
RefillingState --> MovingState : Out of range
RefillingState --> RefillingState : No resources in storage
RefillingState --> RefillingState : Could not withdraw

RepairingState --> RefillingState : No resources\non hand
RepairingState --> IdleState : Nothing\nto repair
RepairingState --> RefillingState : Structure to repair\ndoesn't exist
RepairingState --> RefillingState : Structure repaired
RepairingState --> MovingState : Out of range

IdleState --> RefillingState : No resources\non hand
IdleState --> IdleState : Nothing\nto repair
IdleState --> RefillingState : Structure to repair\ndoesn't exist
IdleState --> RefillingState : Structure repaired
IdleState --> MovingState : Out of range

MovingState --> BuildingState : In range
MovingState --> RefillingState : In range
MovingState --> RepairingState : In range
MovingState --> IdleState : In range
@enduml
