@startmindmap
* Screeps

** Base
*** Automated builder
**** Extensions
***** in checker pattern
***** hardcoded stamps
*** Building search cache
**** Split buildings into categories
**** Use tree-like structures
***** tree per type: storages, roads, factories, mining
**** Keep in global mem
***** Refresh whole when miss?
***** Refresh parts when miss?

** Creeps
*** Scout
**** Further testing

** Multi room
*** Evaluate the room
**** Find best place for Spawn
**** Best resources in the room and surroundings

@endmindmap
